// Code generated by ent, DO NOT EDIT.

package marketplaceitem

const (
	// Label holds the string label denoting the marketplaceitem type in the database.
	Label = "marketplaceitem"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// Table holds the table name of the marketplaceitem in the database.
	Table = "marketplaceitems"
)

// Columns holds all SQL columns for marketplaceitem fields.
var Columns = []string{
	FieldID,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
