// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DomainsColumns holds the columns for the "domains" table.
	DomainsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tenant_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
	}
	// DomainsTable holds the schema information for the "domains" table.
	DomainsTable = &schema.Table{
		Name:       "domains",
		Columns:    DomainsColumns,
		PrimaryKey: []*schema.Column{DomainsColumns[0]},
	}
	// MarketplaceitemsColumns holds the columns for the "marketplaceitems" table.
	MarketplaceitemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString},
	}
	// MarketplaceitemsTable holds the schema information for the "marketplaceitems" table.
	MarketplaceitemsTable = &schema.Table{
		Name:       "marketplaceitems",
		Columns:    MarketplaceitemsColumns,
		PrimaryKey: []*schema.Column{MarketplaceitemsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DomainsTable,
		MarketplaceitemsTable,
	}
)

func init() {
}
